# Generated by Django 3.0.2 on 2020-02-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao_sala', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('lotacao', models.IntegerField()),
                ('laboratorio', models.BooleanField()),
                ('auditorio', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_utilizador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome_utilizador', models.CharField(max_length=50)),
                ('ultimo_nome_utilizador', models.CharField(max_length=50)),
                ('tipo_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Tipo_utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Uc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_uc', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-Feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('hora_inicio', models.CharField(max_length=10)),
                ('hora_fim', models.CharField(max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Sala')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Uc')),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=20)),
                ('pincode_status', models.SmallIntegerField(choices=[(0, 'Off'), (1, 'On')])),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Horario')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Utilizador')),
            ],
        ),
    ]
