# Generated by Django 3.0.2 on 2020-02-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['-nome', '-lotacao']},
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='designacao_sala',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='auditorio',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='laboratorio',
        ),
    ]
