# Generated by Django 3.0.2 on 2020-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20200213_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='utilizador',
            name='username',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
    ]
